frase = 'Curso em Vídeo  Python'
print(frase)
print('A quarta letra é:',frase[3])
print('Da quarta letra até a 12a:', frase[3:13])
print('Do inicio até a 12a:', frase[:13])
print('Da 12a até o final:', frase[13:])
print('Da 2a letra até a 14a letra pulando de dois em dois:',frase[1:15:2])
print('Dentro da frase: Curso em Vídeo  Python existe :',frase.count('o'),' letra o')
print(frase.upper())
print('O tamanho da frase é: ',len(frase))
print(frase.replace('Python', 'Android'))
print(frase)
frase = frase.replace('Python', 'Android')
print(frase)
print('Curso' in frase)
print(frase.find('Curso'))
print(frase.lower().find('vídeo'))
print(frase.split())
dividido = frase.split()
print(dividido)
print(dividido[0])
print(dividido[2][3])
print("""Resumo Indicativo: resume somente os fatos importantes, as principais ideias, sem que haja exemplos oferecidos do texto original. É o tipo de resumo mais pedido nas escolas.
Resumo Informativo: resume as informações e/ou dados qualitativos e quantitativos expressos no texto original. Se confunde com os fichamentos e geralmente são utilizado em textos acadêmicos.
Resumo Crítico: chamado de resenha crítica, ele resume as informações do texto original os quais são acrescentados juízos de valor, ou seja, surge argumentos do autor e do escritor do resumo.""")
